version: '3.8'
services:
  admin_website:
    container_name: admin-website
    restart: always
    build: .
    ports:
      - '3001'
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/.next

networks:
  default:
    external:
      name: backend
