version: '3.8'
services:
  dropgala_admin:
    container_name: admin-website
    restart: always
    build: .
    ports:
      - '3001:3000'
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - ./middleware/jwtRS256.key.pub:/usr/src/app/jwtRS256.key.pub

networks:
  default:
    external:
      name: backend-network
