version: "3.8"
services:
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web-root:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - ./web-root:/var/www/html
    depends_on:
      - webserver

    command:
      certonly --webroot --webroot-path=/var/www/html --email dropgala@gmail.com
      --agree-tos --no-eff-email --force-renewal -d dropgala.com -d
      www.dropgala.com -d api.dropgala.com -d admin.dropgala.com -d
      admin-api.dropgala.com -d media.dropgala.com -d development.dropgala.com

  admin_website:
    container_name: admin-website
    restart: always
    build: .
    ports:
      - "3001"
    volumes:
      - /usr/src/app/node_modules
      - /usr/src/app/.next

  redis:
    image: redis
    container_name: redis_cache
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379"
    restart: always

volumes:
  certbot-etc:
  certbot-var:

networks:
  default:
    external:
      name: backend
