name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy dropgala
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # Ip address of the server you wish to ssh into
          key: ${{ secrets.SSH_KEY }} # Private or public key of the server
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into

          script: |
            eval $(ssh-agent -s)
            ssh-add /home/isaac/.ssh/id_rsa_github
            cd dropgala.com
            git pull origin main
            echo ${{ secrets.USER_PASS }} | sudo -S docker-compose down
            echo ${{ secrets.USER_PASS }} | sudo -S docker-compose up -d --build
            echo 'Deployment successful to digital ocean'
